workflows:
  code-coverage:
    name: Code Coverage
    environment:
      vars:
        CODE_COVERAGE_TARGET: "99"
    scripts:
      - HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov
      - echo "Hello world!"
      - |
        cd $FCI_BUILD_DIR
        flutter test --coverage
      - |
        code_coverage=$(lcov --list $FCI_BUILD_DIR/coverage/lcov.info | sed -n "s/.*Total:|\(.*\)%.*/\1/p")
        echo "Code Coverage: ${code_coverage}%"
        if (( $(echo "$code_coverage < $CODE_COVERAGE_TARGET" | bc) )); then exit 1; fi

