workflows:
  code-coverage:
    name: Code Coverage
    cache:
      cache_paths:
        - $HOME/test
    scripts:
      - HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov
      - echo "Hello world!"
      - |
        cd $FCI_BUILD_DIR
        flutter test --coverage
      - |
        cov=$(lcov --list $FCI_BUILD_DIR/coverage/lcov.info | sed -n "s/.*Total:|\(.*\)%.*/\1/p")
        echo "Code Coverage: ${cov}%"
        if [[ "$cov" -lt 90 ]]; then
          exit 1
        fi

