workflows:
  code-coverage:
    name: Code Coverage
    environment:
      vars:
        CODE_COVERAGE_TARGET: "95"
    scripts:
      - HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov
      - echo "Hello world!"
      - |
        cd $FCI_BUILD_DIR
        flutter test --coverage
      - |
        code_coverage=$(lcov --list $FCI_BUILD_DIR/coverage/lcov.info | sed -n "s/.*Total:|\(.*\)%.*/\1/p")
        echo "Code Coverage: ${code_coverage}%"
        if (( $code_coverage < 95 )); then echo "less 95"; fi
        if (( $code_coverage < 99 )); then echo "less 99"; fi

#        if (( $(echo "$code_coverage < 95" | bc) )); then echo "less 95"; fi
#        if (( $(echo "$code_coverage < 99" | bc) )); then echo "less 99"; fi

