workflows:
  test:
    scripts:
      - |
        #!/bin/sh
        echo "Hello world!"

  codecov-io:
    environment:
      vars:
        CODECOV_TOKEN: "708d523b-db0c-431b-9379-26aac1cb690b"
    scripts:
      - flutter test --coverage
      - curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN -f $FCI_BUILD_DIR/coverage/lcov.info
  code-coverage:
    environment:
      vars:
        CODE_COVERAGE_TARGET: "95"
    scripts:
      - HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov
      - flutter test --coverage
      - |
        code_coverage=$(lcov --list $FCI_BUILD_DIR/coverage/lcov.info | sed -n "s/.*Total:|\(.*\)%.*/\1/p")
        echo "Code Coverage: ${code_coverage}%"
        if (( $(echo "$code_coverage < $CODE_COVERAGE_TARGET" | bc) )); then exit 1; fi

